

export const ADD_USER_INFOR = "ADD_USER_INFOR";
export const CREATE_NEW_ROOM = "CREATE_NEW_ROOM";
export const CREATE_LIST_ROOM = "CREATE_LIST_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
export const JOIN_ROOM = "JOIN_ROOM";
export const PLAY_TURN = "PLAY_TURN";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CREATE_GAME_USER_INFOR = "CREATE_GAME_USER_INFOR";
export const CREATE_RESULT_GAME = "CREATE_RESULT_GAME";
export const CREATE_RANK_USER = "CREATE_RANK_USER";
export const REFRESH_RANK_USER = "REFRESH_RANK_USER";